### Autenticacion correcta
POST http://localhost:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
  "username": "JhousefSilva",
  "passwordd": "test1234"
}


### Autenticacion incorrecta

POST http://192.168.220.161:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
  "username": "JhousefSiwlva",
  "passwordd": "test1234"
}

### Autenticacion con valores vacios
POST http://localhost:7777/api/v1/auth/
content-type: application/json
Accept: application/json

{

}


